import {nanoid} from 'nanoid';

export const videoEntries = [
  {
    id: nanoid(),
    title: '3-Shot-Regel in der Praxis',
    titleShort: '3-Shot-Regel',
    slug: '3-shot-regel-in-der-praxis',
    videoUrl: 'https://vimeo.com/737176389',
    posterFrameUrl: '',
    tag: 'Dreh',
    description:
      'Wenn ich eine Szene drehe, dann immer aus mindestens drei verschiedenen Blickwinkeln. Das macht die Arbeit im Schnitt deutlich einfacher.',
    lowerThirds: [],
    location: 'Berlin',
    author: 'Ben Muster',
    cameraman: 'Stefan L. Schlicker',
    editor: 'Stefan L. Schlicker',
    date: '15. Juli 2022',
    dateUpdated: 'last update: 17. Juli 2022',
    length: '2:30',
    script: [],
  },
  {
    id: nanoid(),
    title: '10 Sekunden - bloss nicht weniger',
    titleShort: '10 Sekunden',
    slug: '10-sekunden-bloss-nicht-weniger',
    videoUrl: 'https://vimeo.com/737176102',
    posterFrameUrl: '',
    tag: 'Dreh',
    description:
      'Wenn man vom Fotogarfieren kommt, ist Filmen am Anfang sehr schwer. Der Fehler, den die meisten machen: zu kurze Szenen drehen. Egal wie schwer es fällt, jedes Bild sollte 10 Sekunden lang sein. Man kann am Anfang auch mitzählen',
    lowerThirds: [],
    location: 'Berlin',
    author: 'Ben Muster',
    cameraman: 'Stefan L. Schlicker',
    editor: 'Stefan L. Schlicker',
    date: '15. Juli 2022',
    dateUpdated: 'last update: 17. Juli 2022',
    length: '2:30',
    script: [],
  },
  {
    id: nanoid(),
    title: 'Immer ein Vorgespräch',
    slug: 'immer-ein-vorgespraech',
    titleShort: 'Vorgespräch',
    videoUrl: 'https://vimeo.com/737175800',
    posterFrameUrl: '',
    tag: 'Produktion',
    description:
      'Wenn ein Fernsehteam dreht, ist Zeit immer knapp. Trotzdem sollte man immer vor den eigentlichen Dreharbeiten mit den Protagonisten sprechen. Das hat viele Vorteile, nicht nur auf der persönlichen Ebene, sondern vor allem für die Bilder selbst.',
    lowerThirds: [],
    location: 'Berlin',
    author: 'Ben Muster',
    cameraman: 'Stefan L. Schlicker',
    editor: 'Stefan L. Schlicker',
    date: '15. Juli 2022',
    dateUpdated: 'last update: 17. Juli 2022',
    length: '2:30',
    script: [],
  },
  {
    id: nanoid(),
    title: 'Es geht auch ohne Drohne',
    titleShort: 'Filmen ohne Drohne',
    slug: 'es-geht-auch-ohne-drohne',
    videoUrl: 'https://vimeo.com/737175602',
    posterFrameUrl: '',
    tag: 'Drohnen',
    description:
      'Bilder von Drohnen sind cool, keine Frage. Aber sie kosten auch Zeit. Unter einer halben Stunde geht nichts. Manchmal reicht es, die Kamera aus dem Fenster zu halten und ein Bild zu machen. Das geht nämlich in ein paar Sekunden, wenn man kein Stativ aufauen muss.',
    lowerThirds: [],
    location: 'Berlin',
    author: 'Ben Muster',
    cameraman: 'Stefan L. Schlicker',
    editor: 'Stefan L. Schlicker',
    date: '15. Juli 2022',
    dateUpdated: 'last update: 17. Juli 2022',
    length: '2:30',
    script: [],
  },
  {
    id: nanoid(),
    title: 'Nahaufnahme sind das Salz in der Suppe',
    titleShort: 'Nahaufnahme',
    slug: 'nahaufnahme-sind-das-salz-in-der-suppe',
    videoUrl: 'https://vimeo.com/737175293',
    posterFrameUrl: '',
    tag: 'Dreh',
    description:
      'Nähe erzeugt Emotionen. Das ist der eigentich "Trick" in Sachen Detailaufnahmen. Doch wie nah soll man an ein Objekt gehen - vor allem, wenn man ein lebendiges Objekt vor der Linse hat.',
    lowerThirds: [],
    location: 'Berlin',
    author: 'Ben Muster',
    cameraman: 'Stefan L. Schlicker',
    editor: 'Stefan L. Schlicker',
    date: '15. Juli 2022',
    dateUpdated: 'last update: 17. Juli 2022',
    length: '2:30',
    script: [],
  },
  {
    id: nanoid(),
    title: 'Filmen in der Industrieproduktion',
    titleShort: 'Industriefilm',
    slug: 'filmen-in-der-industrie-produktion',
    videoUrl: 'https://vimeo.com/737174844',
    posterFrameUrl: '',
    tag: 'Dreh',
    description:
      'Eigentlich ist nichts ist so einfach, wie in einer Industrieprodutkion zu drehen - wenn man die Abläufe kennt. Vieles wiederholt sich. Und dass sogar alle paar Sekunden. Aber das war es auch schon in Sachen "alles einfach". Die Realität sieht anders aus.',
    lowerThirds: [],
    location: 'Berlin',
    author: 'Ben Muster',
    cameraman: 'Stefan L. Schlicker',
    editor: 'Stefan L. Schlicker',
    date: '15. Juli 2022',
    dateUpdated: 'last update: 17. Juli 2022',
    length: '2:30',
    script: [],
  },
  {
    id: nanoid(),
    title: 'Wenig Zeit, viel drehen',
    titleShort: 'Faktor Zeit',
    slug: 'wenig-zeit-viel-drehen',
    videoUrl: 'https://vimeo.com/737173206',
    posterFrameUrl: '',
    tag: 'Zeitmanagement',
    description:
      'Einen ganzen Tag Zeit für Dreharbeiten - perfekt. Leider kommt das selten vor. Vor allem bei Drehs mit Vorständen und Geschäftsführern ist es eher eine halbe Stunde. Um in so einer kurzen Zeit das Optimale herauszuholen, sollte man gut vorbereitet sein.',
    lowerThirds: [],
    location: 'Berlin',
    author: 'Ben Muster',
    cameraman: 'Stefan L. Schlicker',
    editor: 'Stefan L. Schlicker',
    date: '15. Juli 2022',
    dateUpdated: 'last update: 17. Juli 2022',
    length: '2:30',
    script: [],
  },
  {
    id: nanoid(),
    title: 'Ein Bild für den Anfang',
    titleShort: 'Bildauswahl',
    slug: 'ein-bild-fuer-den-anfang',
    videoUrl: 'https://vimeo.com/394421001',
    posterFrameUrl: '',
    tag: 'Schnitt',
    description:
      'Wie macht man einen guten Film? Mit einem Erdbeben starten und dann ganz langsam steigern. Beim Unternehmensfilm ist die Sache naturgemäß schwieriger. Dennoch gibt es einige Tricks, die Zuschauer gleich von der ersten Sekunden in Bann zu ziehen.',
    lowerThirds: [],
    location: 'Berlin',
    author: 'Ben Muster',
    cameraman: 'Stefan L. Schlicker',
    editor: 'Stefan L. Schlicker',
    date: '15. Juli 2022',
    dateUpdated: 'last update: 17. Juli 2022',
    length: '2:30',
    script: [],
  },
  {
    id: nanoid(),
    title: 'Das Prinzip der Augehöhe',
    titleShort: 'Auf Augenhöhe',
    slug: 'das-prinzip-der-augehoehe',
    videoUrl: 'https://vimeo.com/380515825',
    posterFrameUrl: '',
    tag: 'Interview',
    description:
      'Ein paar Zentimeter können einen großen Unterschied machen, wie Zuschauer eine Person wahrnehmen. Deshalb ist es wichtig, immer auf Augenhöhe zu drehen. Sonst wird der Interviewte als "niedlich" wahrgenommen, obwohl das gar nicht explizit gewollt war. Mit Bilder ist es wie mit der Physik: sie haben ihre eigenen Gesetze.',
    lowerThirds: [],
    location: 'Berlin',
    author: 'Ben Muster',
    cameraman: 'Stefan L. Schlicker',
    editor: 'Stefan L. Schlicker',
    date: '15. Juli 2022',
    dateUpdated: 'last update: 17. Juli 2022',
    length: '2:30',
    script: [],
  },
  {
    id: nanoid(),
    title: 'Mit mehreren Kameras drehen',
    titleShort: 'Multicam Dreh',
    slug: 'das-prinzip-der-augehoehe',
    videoUrl: 'https://vimeo.com/380441214',
    posterFrameUrl: '',
    tag: 'Dreh',
    description:
      'Mit einer Kamera ist man gut beschäftigt. Aber manchmal ist eine Kamera nicht ausreichend. Eine zweite Kamera fürs Interview. Vielleicht noch eine Gopro dazu. Und schon droht Chaos. Da hilft nur, Ruhe zu bewahren.',
    lowerThirds: [],
    location: 'Berlin',
    author: 'Ben Muster',
    cameraman: 'Stefan L. Schlicker',
    editor: 'Stefan L. Schlicker',
    date: '15. Juli 2022',
    dateUpdated: 'last update: 17. Juli 2022',
    length: '2:30',
    script: [],
  },
];
